const http = require('http');
const fs = require('fs');
const os = require('os');
const PORT = 3131;

function getSessions() {
  try {
    const p = os.homedir() + '/.openclaw/agents/main/sessions/sessions.json';
    const d = JSON.parse(fs.readFileSync(p, 'utf8'));
    return Object.entries(d).map(([key, v]) => {
      const ms = Date.now() - new Date(v.updatedAt || v.createdAt || Date.now()).getTime();
      const m = Math.floor(ms / 60000);
      return { key, model: v.model || 'gpt-4o', age: m < 60 ? m + 'm' : Math.floor(m/60) + 'h', tokenPct: Math.round(((v.tokenCount||0)/(v.contextWindow||128000))*100) };
    });
  } catch(e) { return []; }
}

function getMemory() {
  try {
    const base = os.homedir() + '/AgentWorkspace/memory';
    if (!fs.existsSync(base)) return [];
    return fs.readdirSync(base).filter(f => f.endsWith('.md') || f.endsWith('.txt')).map(f => {
      const c = fs.readFileSync(base + '/' + f, 'utf8');
      return { file: f, preview: c.slice(0, 300), size: c.length, lines: c.split('\n').length };
    });
  } catch(e) { return []; }
}

async function pingOllama() {
  return new Promise(resolve => {
    const r = http.get({ hostname:'127.0.0.1', port:11434, path:'/api/tags', timeout:2000 }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => { try { resolve(JSON.parse(d)); } catch(e) { resolve(null); } });
    });
    r.on('error', () => resolve(null));
    r.on('timeout', () => { r.destroy(); resolve(null); });
  });
}

async function pingGateway() {
  return new Promise(resolve => {
    const r = http.get({ hostname:'127.0.0.1', port:8188, path:'/health', timeout:2000, headers: { Authorization: 'Bearer ski-local-fresh-001' } }, res => resolve(res.statusCode < 500));
    r.on('error', () => resolve(false));
    r.on('timeout', () => { r.destroy(); resolve(false); });
  });
}

function buildHTML() {
  const p = [];
  p.push(`<!DOCTYPE html>`);
  p.push(`<html lang=en>`);
  p.push(`<head>`);
  p.push(`<meta charset=UTF-8><meta name=viewport content='width=device-width,initial-scale=1'>`);
  p.push(`<title>Ski Mission Control</title>`);
  p.push(`<link href='https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap' rel=stylesheet>`);
  p.push(`<style>`);
  p.push(`*{margin:0;padding:0;box-sizing:border-box}`);
  p.push(`:root{--bg:#0b0e11;--c1:#161a1f;--c2:#1e2329;--c3:#252c35;--c4:#2d3540;--border:#2b3139;--border2:#3c4451;--t1:#eaecef;--t2:#848e9c;--t3:#5a6375;--t4:#2b3139;--yn:#f0b90b;--yn2:rgba(240,185,11,0.12);--yn3:rgba(240,185,11,0.25);--gr:#0ecb81;--gr2:rgba(14,203,129,0.12);--ro:#f6465d;--ro2:rgba(246,70,93,0.12);--bl:#1677ff;--bl2:rgba(22,119,255,0.12);--pu:#c084fc;--pu2:rgba(192,132,252,0.12)}`);
  p.push(`body{background:var(--bg);color:var(--t1);font-family:'IBM Plex Sans',sans-serif;font-size:13px;display:flex;flex-direction:column;height:100vh;overflow:hidden}`);
  p.push(`.ticker{height:36px;background:var(--c1);border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 16px;gap:24px;overflow:hidden;flex-shrink:0}`);
  p.push(`.tick-item{display:flex;align-items:center;gap:6px;font-family:'IBM Plex Mono',monospace;font-size:11px;white-space:nowrap;flex-shrink:0}`);
  p.push(`.tick-name{color:var(--t2)}.tick-val{color:var(--t1);font-weight:500}.tick-chg.up{color:var(--gr)}.tick-chg.dn{color:var(--ro)}.tick-sep{color:var(--t4);margin:0 2px}`);
  p.push(`.ticker-scroll{display:flex;gap:24px;align-items:center;animation:tickscroll 30s linear infinite}`);
  p.push(`@keyframes tickscroll{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}`);
  p.push(`.layout{flex:1;display:flex;overflow:hidden}`);
  p.push(`aside{width:200px;min-width:200px;background:var(--c1);border-right:1px solid var(--border);display:flex;flex-direction:column;overflow:hidden}`);
  p.push(`.brand{display:flex;align-items:center;gap:10px;padding:12px 14px 10px;border-bottom:1px solid var(--border)}`);
  p.push(`.brand-ico{width:28px;height:28px;background:var(--yn);border-radius:5px;display:flex;align-items:center;justify-content:center;font-size:14px;flex-shrink:0;color:#000}`);
  p.push(`.brand-name{font-size:13px;font-weight:600;letter-spacing:-.2px}.brand-ver{font-size:9px;color:var(--t3);font-family:'IBM Plex Mono',monospace;letter-spacing:.5px}`);
  p.push(`.nav-scroll{flex:1;overflow-y:auto;padding:4px 0}.nav-scroll::-webkit-scrollbar{width:0}`);
  p.push(`.grp{padding:12px 12px 3px;font-size:9px;letter-spacing:1px;text-transform:uppercase;color:var(--t4);font-family:'IBM Plex Mono',monospace}`);
  p.push(`.nav{display:flex;align-items:center;gap:7px;padding:6px 10px;margin:0 4px;border-radius:4px;cursor:pointer;color:var(--t2);font-size:12px;transition:all .1s;user-select:none;border:1px solid transparent}`);
  p.push(`.nav:hover{background:var(--c2);color:var(--t1)}.nav.active{background:var(--c2);color:var(--yn);border-color:var(--border)}`);
  p.push(`.nav-ic{width:14px;text-align:center;font-size:12px;flex-shrink:0}`);
  p.push(`.nav-bd{margin-left:auto;background:var(--c3);padding:1px 6px;border-radius:3px;font-size:9px;font-family:'IBM Plex Mono',monospace;color:var(--t3)}`);
  p.push(`.foot{padding:8px;border-top:1px solid var(--border)}`);
  p.push(`.status-box{background:var(--c2);border:1px solid var(--border);border-radius:4px;padding:7px 10px;display:flex;flex-direction:column;gap:4px}`);
  p.push(`.stat-row{display:flex;align-items:center;justify-content:space-between}`);
  p.push(`.stat-lbl{font-size:10px;color:var(--t3);font-family:'IBM Plex Mono',monospace}`);
  p.push(`.stat-val{font-size:10px;font-family:'IBM Plex Mono',monospace;font-weight:500}`);
  p.push(`.stat-val.on{color:var(--gr)}.stat-val.off{color:var(--ro)}.stat-val.yn{color:var(--yn)}`);
  p.push(`.dot{width:5px;height:5px;border-radius:50%;display:inline-block;margin-right:4px}`);
  p.push(`.dot.on{background:var(--gr);box-shadow:0 0 4px var(--gr)}.dot.off{background:var(--ro)}.dot.yn{background:var(--yn);box-shadow:0 0 4px var(--yn)}`);
  p.push(`.main{flex:1;display:flex;flex-direction:column;overflow:hidden}`);
  p.push(`.topbar{height:44px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;padding:0 18px;background:var(--c1);flex-shrink:0}`);
  p.push(`.top-l{display:flex;align-items:center;gap:6px;font-family:'IBM Plex Mono',monospace;font-size:11px;color:var(--t2)}`);
  p.push(`.top-title{color:var(--t1);font-weight:500;font-family:'IBM Plex Sans',sans-serif;font-size:13px}`);
  p.push(`.top-r{display:flex;align-items:center;gap:6px}`);
  p.push(`.btn{display:inline-flex;align-items:center;gap:4px;padding:5px 12px;border-radius:4px;border:1px solid var(--border);background:var(--c2);color:var(--t2);font-size:11px;cursor:pointer;font-family:'IBM Plex Sans',sans-serif;transition:all .1s;font-weight:500}`);
  p.push(`.btn:hover{border-color:var(--border2);color:var(--t1)}.btn.yn{background:var(--yn);border-color:var(--yn);color:#000;font-weight:600}.btn.yn:hover{opacity:.9}`);
  p.push(`.clk{font-family:'IBM Plex Mono',monospace;font-size:11px;color:var(--t3)}`);
  p.push(`.pages{flex:1;overflow:hidden}.page{display:none;height:100%;overflow-y:auto;padding:18px}.page::-webkit-scrollbar{width:3px}.page::-webkit-scrollbar-thumb{background:var(--c4);border-radius:2px}.page.show{display:block}`);
  p.push(`.ph{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}`);
  p.push(`.ptitle{font-size:15px;font-weight:600;letter-spacing:-.3px}.pmeta{font-size:10px;color:var(--t3);font-family:'IBM Plex Mono',monospace}`);
  p.push(`.chip{padding:1px 6px;border-radius:3px;font-size:10px;font-family:'IBM Plex Mono',monospace;border:1px solid transparent;font-weight:500}`);
  p.push(`.chip.gr{background:var(--gr2);color:var(--gr);border-color:rgba(14,203,129,.3)}.chip.ro{background:var(--ro2);color:var(--ro);border-color:rgba(246,70,93,.3)}.chip.yn{background:var(--yn2);color:var(--yn);border-color:var(--yn3)}.chip.bl{background:var(--bl2);color:var(--bl);border-color:rgba(22,119,255,.3)}.chip.pu{background:var(--pu2);color:var(--pu);border-color:rgba(192,132,252,.3)}.chip.gr2{background:var(--c3);color:var(--t2);border-color:var(--border)}`);
  p.push(`.mrow{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-bottom:14px}`);
  p.push(`.met{background:var(--c2);border:1px solid var(--border);border-radius:5px;padding:12px 14px;transition:border-color .1s}.met:hover{border-color:var(--border2)}`);
  p.push(`.mval{font-size:18px;font-weight:600;font-family:'IBM Plex Mono',monospace;letter-spacing:-.5px;line-height:1;margin-bottom:2px}`);
  p.push(`.mval.gr{color:var(--gr)}.mval.ro{color:var(--ro)}.mval.yn{color:var(--yn)}.mval.bl{color:var(--bl)}`);
  p.push(`.mlbl{font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.8px;font-family:'IBM Plex Mono',monospace}`);
  p.push(`.msub{font-size:9px;color:var(--t2);font-family:'IBM Plex Mono',monospace;margin-top:2px}`);
  p.push(`.board{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}`);
  p.push(`.bcol{background:var(--c1);border:1px solid var(--border);border-radius:5px;overflow:hidden}`);
  p.push(`.bch{padding:8px 12px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;background:var(--c2)}`);
  p.push(`.bct{display:flex;align-items:center;gap:6px;font-size:11px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;font-family:'IBM Plex Mono',monospace}`);
  p.push(`.bcc{font-size:10px;font-family:'IBM Plex Mono',monospace;color:var(--t3);background:var(--c3);padding:1px 6px;border-radius:3px}`);
  p.push(`.cdot{width:6px;height:6px;border-radius:50%;flex-shrink:0}`);
  p.push(`.bcb{padding:6px;display:flex;flex-direction:column;gap:4px;min-height:80px}`);
  p.push(`.tc{background:var(--c2);border:1px solid var(--border);border-radius:4px;padding:9px 10px;cursor:pointer;transition:all .1s}`);
  p.push(`.tc:hover{border-color:var(--border2);background:var(--c3)}`);
  p.push(`.tc-id{font-family:'IBM Plex Mono',monospace;font-size:9px;color:var(--t3);margin-bottom:2px;text-transform:uppercase;letter-spacing:.5px}`);
  p.push(`.tc-name{font-size:11px;font-weight:500;color:var(--t1);margin-bottom:5px;line-height:1.4}`);
  p.push(`.tc-bot{display:flex;align-items:center;justify-content:space-between}.tc-chips{display:flex;gap:3px;flex-wrap:wrap}.tc-age{font-size:9px;font-family:'IBM Plex Mono',monospace;color:var(--t3)}`);
  p.push(`.tbar{height:2px;background:var(--c4);border-radius:2px;margin-top:5px;overflow:hidden}.tbf{height:100%;background:var(--gr);border-radius:2px;transition:width .5s}.tbf.yn{background:var(--yn)}.tbf.ro{background:var(--ro)}`);
  p.push(`.empty{padding:18px;text-align:center;color:var(--t3);font-size:11px}.empty-i{font-size:16px;margin-bottom:4px;opacity:.4}`);
  p.push(`.divl{height:1px;background:var(--border);margin:14px 0}`);
  p.push(`.inp{background:var(--c3);border:1px solid var(--border);border-radius:4px;padding:7px 11px;color:var(--t1);font-family:'IBM Plex Sans',sans-serif;font-size:12px;outline:none;transition:border-color .1s;width:100%}.inp:focus{border-color:var(--yn)}.inp::placeholder{color:var(--t3)}`);
  p.push(`.feed-box{background:var(--c1);border:1px solid var(--border);border-radius:5px;overflow:hidden;margin-top:12px}`);
  p.push(`.feed-h{padding:7px 12px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;background:var(--c2)}`);
  p.push(`.feed-ht{font-size:11px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;font-family:'IBM Plex Mono',monospace}`);
  p.push(`.feed-live{display:flex;align-items:center;gap:4px;font-size:9px;font-family:'IBM Plex Mono',monospace;color:var(--gr)}`);
  p.push(`.feed-b{padding:4px;max-height:140px;overflow-y:auto;display:flex;flex-direction:column;gap:0}.feed-b::-webkit-scrollbar{width:2px}.feed-b::-webkit-scrollbar-thumb{background:var(--c4)}`);
  p.push(`.fl{display:flex;gap:8px;padding:3px 7px;border-radius:3px;font-family:'IBM Plex Mono',monospace;font-size:10px}.fl:hover{background:var(--c2)}`);
  p.push(`.ft{color:var(--t4);flex-shrink:0;font-size:9px;padding-top:1px}.fm{color:var(--t2);flex:1}.fm.ok{color:var(--gr)}.fm.warn{color:var(--yn)}.fm.err{color:var(--ro)}.fm.info{color:var(--bl)}`);
  p.push(`.cal7{display:grid;grid-template-columns:repeat(7,1fr);gap:3px}`);
  p.push(`.calhd{text-align:center;font-size:9px;color:var(--t3);font-family:'IBM Plex Mono',monospace;padding:5px 0;text-transform:uppercase;letter-spacing:.5px}`);
  p.push(`.calday{background:var(--c2);border:1px solid var(--border);border-radius:4px;padding:7px;min-height:62px;cursor:pointer;transition:border-color .1s}.calday:hover{border-color:var(--border2)}.calday.today{border-color:var(--yn3);background:var(--yn2)}.calday.faded{opacity:.25}`);
  p.push(`.caldn{font-size:10px;font-family:'IBM Plex Mono',monospace;margin-bottom:3px}.calday.today .caldn{color:var(--yn);font-weight:600}`);
  p.push(`.calev{font-size:9px;padding:1px 4px;border-radius:2px;margin-bottom:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.calev.yn{background:var(--yn2);color:var(--yn)}.calev.gr{background:var(--gr2);color:var(--gr)}`);
  p.push(`.pgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}`);
  p.push(`.pj{background:var(--c2);border:1px solid var(--border);border-radius:5px;padding:14px;cursor:pointer;transition:all .15s}.pj:hover{border-color:var(--border2);transform:translateY(-1px)}`);
  p.push(`.pj-top{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:8px}`);
  p.push(`.pj-ico{width:32px;height:32px;border-radius:5px;display:flex;align-items:center;justify-content:center;font-size:16px}`);
  p.push(`.pj-name{font-size:13px;font-weight:600;margin-bottom:2px}.pj-desc{font-size:11px;color:var(--t2);line-height:1.5;margin-bottom:10px}`);
  p.push(`.pbar{height:3px;background:var(--c4);border-radius:2px;overflow:hidden;margin-top:4px}.pfill{height:100%;border-radius:2px;transition:width .6s}`);
  p.push(`.plbl{display:flex;justify-content:space-between;font-size:9px;font-family:'IBM Plex Mono',monospace;color:var(--t3);margin-top:3px}`);
  p.push(`.addbox{background:var(--c2);border:1px dashed var(--border);border-radius:5px;padding:22px;text-align:center;cursor:pointer;transition:all .15s;color:var(--t3)}.addbox:hover{border-color:var(--yn3);color:var(--yn)}`);
  p.push(`.airow{display:flex;align-items:flex-start;gap:9px;padding:8px 10px;border-radius:4px;border:1px solid var(--border);background:var(--c2);margin-bottom:5px;cursor:pointer;transition:all .1s}.airow:hover{border-color:var(--yn3);background:var(--yn2)}`);
  p.push(`.ai-ico{font-size:14px;flex-shrink:0;margin-top:1px}.ai-txt{font-size:11px;line-height:1.5}.ai-sub{font-size:9px;color:var(--t3);font-family:'IBM Plex Mono',monospace;margin-top:2px;text-transform:uppercase;letter-spacing:.3px}`);
  p.push(`.memcard{background:var(--c2);border:1px solid var(--border);border-radius:4px;padding:10px 12px;margin-bottom:5px;cursor:pointer;transition:border-color .1s}.memcard:hover{border-color:var(--border2)}`);
  p.push(`.memfile{font-size:10px;font-family:'IBM Plex Mono',monospace;color:var(--yn);margin-bottom:3px;text-transform:uppercase;letter-spacing:.3px}.memprev{font-size:11px;color:var(--t2);line-height:1.5;white-space:pre-wrap;word-break:break-word}.memmeta{font-size:9px;color:var(--t3);font-family:'IBM Plex Mono',monospace;margin-top:4px}`);
  p.push(`.doc-table{width:100%;border-collapse:collapse}`);
  p.push(`.doc-table th{text-align:left;padding:7px 12px;font-size:9px;color:var(--t3);font-family:'IBM Plex Mono',monospace;text-transform:uppercase;letter-spacing:.8px;border-bottom:1px solid var(--border);background:var(--c2)}`);
  p.push(`.doc-table td{padding:9px 12px;font-size:11px;border-bottom:1px solid var(--border);background:var(--c1);transition:background .1s}`);
  p.push(`.doc-table tr:hover td{background:var(--c2)}.doc-table tr:last-child td{border-bottom:none}`);
  p.push(`.tgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:14px}`);
  p.push(`.agcard{background:var(--c2);border:1px solid var(--border);border-radius:5px;padding:12px;transition:all .15s}.agcard:hover{border-color:var(--border2)}.agcard.me{border-color:var(--yn3);background:var(--yn2)}`);
  p.push(`.ag-top{display:flex;align-items:center;gap:9px;margin-bottom:8px}.ag-av{width:34px;height:34px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:16px;flex-shrink:0}`);
  p.push(`.ag-name{font-size:13px;font-weight:600}.ag-role{font-size:9px;color:var(--t3);font-family:'IBM Plex Mono',monospace;text-transform:uppercase;letter-spacing:.5px}.ag-task{font-size:11px;color:var(--t2);line-height:1.5;margin-bottom:7px}`);
  p.push(`.mod-table{width:100%;border-collapse:collapse}`);
  p.push(`.mod-table th{text-align:left;padding:8px 14px;font-size:9px;color:var(--t3);font-family:'IBM Plex Mono',monospace;text-transform:uppercase;letter-spacing:.8px;border-bottom:1px solid var(--border);background:var(--c2)}`);
  p.push(`.mod-table td{padding:11px 14px;font-size:12px;border-bottom:1px solid var(--border);background:var(--c1);transition:background .1s}`);
  p.push(`.mod-table tr:hover td{background:var(--c2)}.mod-table tr:last-child td{border-bottom:none}`);
  p.push(`.mod-name{font-weight:600;font-size:13px}.mod-desc{font-size:10px;color:var(--t3);margin-top:1px}`);
  p.push(`.mod-cost{font-family:'IBM Plex Mono',monospace;color:var(--gr);font-size:11px}.mod-ctx{font-family:'IBM Plex Mono',monospace;color:var(--t2);font-size:11px}`);
  p.push(`.ollama-box{background:var(--c2);border:1px solid var(--border);border-radius:5px;overflow:hidden;margin-bottom:14px}`);
  p.push(`.ollama-h{padding:8px 14px;border-bottom:1px solid var(--border);background:var(--c3);display:flex;align-items:center;justify-content:space-between}`);
  p.push(`.ollama-ht{font-size:11px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;font-family:'IBM Plex Mono',monospace}`);
  p.push(`.ollama-row{display:flex;align-items:center;gap:12px;padding:9px 14px;border-bottom:1px solid var(--border);transition:background .1s}.ollama-row:hover{background:var(--c3)}.ollama-row:last-child{border-bottom:none}`);
  p.push(`.ol-name{font-size:12px;font-weight:500;flex:1}.ol-size{font-size:10px;font-family:'IBM Plex Mono',monospace;color:var(--t3);min-width:60px}.ol-status{font-size:10px;font-family:'IBM Plex Mono',monospace}`);
  p.push(`.offc{display:flex;flex-direction:column;align-items:center}`);
  p.push(`#cv{border:1px solid var(--border);border-radius:5px;image-rendering:pixelated}`);
  p.push(`.legend{display:flex;gap:14px;margin-top:8px;font-size:10px;color:var(--t2);flex-wrap:wrap;justify-content:center;font-family:'IBM Plex Mono',monospace}`);
  p.push(`.leg{display:flex;align-items:center;gap:5px}.leg-d{width:9px;height:9px;border-radius:2px;flex-shrink:0}`);
  p.push(`.overlay{position:fixed;inset:0;background:rgba(0,0,0,.7);z-index:999;display:flex;align-items:center;justify-content:center;opacity:0;pointer-events:none;transition:opacity .15s}.overlay.open{opacity:1;pointer-events:all}`);
  p.push(`.modal{background:var(--c2);border:1px solid var(--border2);border-radius:6px;padding:20px;width:400px;max-width:92vw}`);
  p.push(`.modal-t{font-size:14px;font-weight:600;margin-bottom:14px;letter-spacing:-.2px}.mrow2{margin-bottom:10px}.mlbl{font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.8px;margin-bottom:4px;font-family:'IBM Plex Mono',monospace}`);
  p.push(`.mact{display:flex;justify-content:flex-end;gap:6px;margin-top:14px}`);
  p.push(`</style>`);
  p.push(`</head>`);
  p.push(`<body>`);
  p.push(`<div class=ticker>`);
  p.push(`<div class=ticker-scroll id=ticker-scroll>`);
  p.push(`<div class=tick-item><span class=tick-name>GATEWAY</span><span class=tick-sep>|</span><span class=tick-val id=tk-gw>CHECKING</span></div>`);
  p.push(`<div class=tick-item><span class=tick-name>SESSIONS</span><span class=tick-sep>|</span><span class=tick-val id=tk-sess>-</span></div>`);
  p.push(`<div class=tick-item><span class=tick-name>OLLAMA</span><span class=tick-sep>|</span><span class=tick-val id=tk-ol>CHECKING</span></div>`);
  p.push(`<div class=tick-item><span class=tick-name>PRIMARY</span><span class=tick-sep>|</span><span class=tick-val>Claude Sonnet</span></div>`);
  p.push(`<div class=tick-item><span class=tick-name>CRON</span><span class=tick-sep>|</span><span class=tick-val id=tk-cron>2 JOBS</span></div>`);
  p.push(`<div class=tick-item><span class=tick-name>MEMORY</span><span class=tick-sep>|</span><span class=tick-val>4 FILES</span></div>`);
  p.push(`<div class=tick-item><span class=tick-name>TELEGRAM</span><span class=tick-sep>|</span><span class=tick-val id=tk-tg>LIVE</span></div>`);
  p.push(`<div class=tick-item><span class=tick-name>MORNING-BRIEF</span><span class=tick-sep>|</span><span class=tick-val>08:00 MMT</span></div>`);
  p.push(`</div></div>`);
  p.push(`<div class=layout>`);
  p.push(`<aside>`);
  p.push(`<div class=brand><div class=brand-ico>S</div><div><div class=brand-name>Ski Control</div><div class=brand-ver>OPENCLAW 2026.3</div></div></div>`);
  p.push(`<div class=nav-scroll>`);
  p.push(`<div class=grp>Workspace</div>`);
  p.push(`<div class='nav active' data-p=board><span class=nav-ic>&#9632;</span>Taskboard<span class=nav-bd id=nb-b>-</span></div>`);
  p.push(`<div class=nav data-p=cal><span class=nav-ic>&#128197;</span>Calendar<span class=nav-bd>2</span></div>`);
  p.push(`<div class=nav data-p=proj><span class=nav-ic>&#128640;</span>Projects<span class=nav-bd id=nb-p>3</span></div>`);
  p.push(`<div class=grp>Intelligence</div>`);
  p.push(`<div class=nav data-p=ai><span class=nav-ic>&#10022;</span>AI Extensions</div>`);
  p.push(`<div class=nav data-p=mem><span class=nav-ic>&#129504;</span>Memory<span class=nav-bd id=nb-m>-</span></div>`);
  p.push(`<div class=nav data-p=docs><span class=nav-ic>&#128196;</span>Documents</div>`);
  p.push(`<div class=nav data-p=live><span class=nav-ic>&#9889;</span>Live Activity<span class=nav-bd id=nb-live>0</span></div>`);
  p.push(`<div class=grp>System</div>`);
  p.push(`<div class=nav data-p=team><span class=nav-ic>&#128101;</span>Team</div>`);
  p.push(`<div class=nav data-p=ollama><span class=nav-ic>&#129422;</span>Ollama<span class=nav-bd id=nb-ol>-</span></div>`);
  p.push(`<div class=nav data-p=office><span class=nav-ic>&#127970;</span>Office</div>`);
  p.push(`<div class=nav data-p=models><span class=nav-ic>&#9000;</span>Models<span class=nav-bd>5</span></div>`);
  p.push(`<div class=grp>Quick</div>`);
  p.push(`<div class=nav data-a=restart><span class=nav-ic>&#8635;</span>Restart Gateway</div>`);
  p.push(`<div class=nav data-a=brief><span class=nav-ic>&#9728;</span>Morning Brief</div>`);
  p.push(`<div class=nav data-a=clear><span class=nav-ic>&#128465;</span>Clear Sessions</div>`);
  p.push(`</div>`);
  p.push(`<div class=foot>`);
  p.push(`<div class=status-box>`);
  p.push(`<div class=stat-row><span class=stat-lbl>GATEWAY</span><span class=stat-val id=gwtxt><span class='dot off' id=gwdot></span>...</span></div>`);
  p.push(`<div class=stat-row><span class=stat-lbl>OLLAMA</span><span class=stat-val id=oltxt><span class='dot off' id=oldot></span>...</span></div>`);
  p.push(`<div class=stat-row><span class=stat-lbl>TIME</span><span class='stat-val yn' id=clk>--:--:--</span></div>`);
  p.push(`</div></div>`);
  p.push(`</aside>`);
  p.push(`<div class=main>`);
  p.push(`<div class=topbar>`);
  p.push(`<div class=top-l><span>Ski</span><span style='color:var(--t4);margin:0 4px'>/</span><span class=top-title id=ptitle>Live Activity</span></div>`);
  p.push(`<div class=top-r><button class=btn id=btn-rf>&#8635; Refresh</button><button class='btn yn' id=btn-new>+ New Task</button></div>`);
  p.push(`</div>`);
  p.push(`<div class=pages>`);
  p.push(`<div class='page' id=page-board>`);
  p.push(`<div class=mrow>`);
  p.push(`<div class=met><div class='mval bl' id=m-sess>-</div><div class=mlbl>Sessions</div></div>`);
  p.push(`<div class=met><div class='mval yn' id=m-cron>2</div><div class=mlbl>Cron Jobs</div></div>`);
  p.push(`<div class=met><div class=mval id=m-model style='font-size:11px'>Claude Sonnet</div><div class=mlbl>Primary</div></div>`);
  p.push(`<div class=met><div class='mval gr' id=m-gw-val>OK</div><div class=mlbl>Gateway</div><div class=msub id=m-gw>port 8188</div></div>`);
  p.push(`<div class=met><div class='mval yn' id=m-tok>-</div><div class=mlbl>Avg Ctx</div></div>`);
  p.push(`<div class=met><div class='mval gr' id=m-ol-val>-</div><div class=mlbl>Ollama</div><div class=msub id=m-ol-sub>:11434</div></div>`);
  p.push(`</div>`);
  p.push(`<div class=board>`);
  p.push(`<div class=bcol><div class=bch><div class=bct><div class=cdot style='background:var(--bl)'></div>Active</div><span class=bcc id=c0>-</span></div><div class=bcb id=col0><div class=empty><div class=empty-i>&#128172;</div>Loading...</div></div></div>`);
  p.push(`<div class=bcol><div class=bch><div class=bct><div class=cdot style='background:var(--gr)'></div>Telegram</div><span class=bcc id=c1>-</span></div><div class=bcb id=col1><div class=empty><div class=empty-i>&#9992;</div>Loading...</div></div></div>`);
  p.push(`<div class=bcol><div class=bch><div class=bct><div class=cdot style='background:var(--yn)'></div>Scheduled</div><span class=bcc id=c2>-</span></div><div class=bcb id=col2><div class=empty><div class=empty-i>&#8987;</div>Loading...</div></div></div>`);
  p.push(`<div class=bcol><div class=bch><div class=bct><div class=cdot style='background:var(--ro)'></div>Action Needed</div><span class=bcc id=c3>2</span></div><div class=bcb id=col3>`);
  p.push(`<div class=tc style='border-color:rgba(246,70,93,.35)'><div class=tc-id>SEC-001</div><div class=tc-name>Rotate OpenAI API key</div><div class=tc-bot><div class=tc-chips><span class='chip ro'>urgent</span></div><div class=tc-age>security</div></div></div>`);
  p.push(`<div class=tc style='border-color:rgba(192,132,252,.35)'><div class=tc-id>SYS-002</div><div class=tc-name>Claude Sonnet active - test it!</div><div class=tc-bot><div class=tc-chips><span class='chip pu'>done</span></div><div class=tc-age>new</div></div></div>`);
  p.push(`</div></div>`);
  p.push(`</div>`);
  p.push(`<div class=feed-box><div class=feed-h><span class=feed-ht>Live Feed</span><div class=feed-live><div class='dot on'></div>LIVE</div></div><div class=feed-b id=feed></div></div>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-cal>`);
  p.push(`<div class=ph><div style='display:flex;align-items:center;gap:8px'><button class=btn id=cal-prev>&#8592;</button><div class=ptitle id=cal-title></div><button class=btn id=cal-next>&#8594;</button></div><div class=pmeta>CRON EVENTS</div></div>`);
  p.push(`<div class=cal7 id=cal-hd></div><div class=cal7 style='margin-top:3px' id=cal-body></div>`);
  p.push(`<div class=divl></div>`);
  p.push(`<div class=ph><div class=ptitle>Upcoming</div></div>`);
  p.push(`<table class=doc-table><thead><tr><th>Job</th><th>Schedule</th><th>Model</th><th>Status</th></tr></thead><tbody>`);
  p.push(`<tr><td><strong>morning-brief-v4</strong></td><td>08:00 MMT daily</td><td>openai/gpt-4o</td><td><span class='chip gr'>OK</span></td></tr>`);
  p.push(`<tr><td><strong>day-summary</strong></td><td>20:00 MMT daily</td><td>default</td><td><span class='chip gr'>OK</span></td></tr>`);
  p.push(`</tbody></table>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-proj>`);
  p.push(`<div class=ph><div class=ptitle>Projects</div><button class='btn yn' id=btn-proj>+ New Project</button></div>`);
  p.push(`<div class=pgrid id=proj-grid></div>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-ai>`);
  p.push(`<div class=ph><div class=ptitle>AI Extensions</div><span class='chip gr'>LIVE</span></div>`);
  p.push(`<div style='display:grid;grid-template-columns:2fr 1fr;gap:12px'>`);
  p.push(`<div>`);
  p.push(`<div style='background:var(--c2);border:1px solid var(--border);border-radius:5px;overflow:hidden;margin-bottom:12px'>`);
  p.push(`<div style='padding:8px 14px;border-bottom:1px solid var(--border);background:var(--c3);display:flex;align-items:center;justify-content:space-between'><span style='font-size:11px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;font-family:IBM Plex Mono,monospace'>Task Suggestions</span><span class='chip yn'>AI</span></div>`);
  p.push(`<div style='padding:8px' id=ai-sugs></div>`);
  p.push(`</div>`);
  p.push(`</div>`);
  p.push(`<div>`);
  p.push(`<div style='background:var(--c2);border:1px solid var(--border);border-radius:5px;overflow:hidden;margin-bottom:12px'>`);
  p.push(`<div style='padding:8px 14px;border-bottom:1px solid var(--border);background:var(--c3)'><span style='font-size:11px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;font-family:IBM Plex Mono,monospace'>Focus</span></div>`);
  p.push(`<div style='padding:8px' id=ai-focus></div></div>`);
  p.push(`<div style='background:var(--c2);border:1px solid var(--border);border-radius:5px;overflow:hidden'>`);
  p.push(`<div style='padding:8px 14px;border-bottom:1px solid var(--border);background:var(--c3)'><span style='font-size:11px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;font-family:IBM Plex Mono,monospace'>Categories</span></div>`);
  p.push(`<div style='padding:8px' id=ai-cats></div></div>`);
  p.push(`</div></div>`);
  p.push(`</div>`);
  p.push(`<div class='page show' id=page-live>`);
  p.push(`<div class=ph><div class=ptitle>Live Activity</div><div style='display:flex;align-items:center;gap:6px'><div class='dot on' id=ws-dot></div><span class='chip gr' id=ws-status>Connecting...</span></div></div>`);
  p.push(`<div class=mrow>`);
  p.push(`<div class=met><div class='mval gr' id=live-acts>0</div><div class=mlbl>Activities</div></div>`);
  p.push(`<div class=met><div class='mval bl' id=live-tools>0</div><div class=mlbl>Tool Calls</div></div>`);
  p.push(`<div class=met><div class='mval yn' id=live-api>0</div><div class=mlbl>API Calls</div></div>`);
  p.push(`<div class=met><div class='mval pu' id=live-files>0</div><div class=mlbl>File Edits</div></div>`);
  p.push(`<div class=met><div class='mval gr2' id=live-errs>0</div><div class=mlbl>Errors</div></div>`);
  p.push(`<div class=met><div class='mval yn' id=live-health>100%</div><div class=mlbl>Health</div></div>`);
  p.push(`</div>`);
  p.push(`<div style='background:var(--c2);border:1px solid var(--border);border-radius:5px;padding:12px;margin-bottom:12px'>`);
  p.push(`<div style='font-size:11px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;font-family:IBM Plex Mono,monospace;margin-bottom:10px'>Activity Stream</div>`);
  p.push(`<div id=live-stream style='max-height:600px;overflow-y:auto;font-family:IBM Plex Mono,monospace'>`);
  p.push(`<div style='background:var(--c3);border:1px solid var(--border);border-radius:4px;padding:8px;margin-bottom:6px;font-size:11px'>`);
  p.push(`  <div style='display:flex;align-items:center;gap:6px'><span>✅</span><span class='chip bl' style='font-size:9px'>tool result</span><span style='color:var(--t3);margin-left:auto'>00:49:32</span></div>`);
  p.push(`  <div style='color:var(--t3);margin-top:3px'>Tool: browser | Status: completed</div>`);
  p.push(`</div>`);
  p.push(`<div style='background:var(--c3);border:1px solid var(--border);border-radius:4px;padding:8px;margin-bottom:6px;font-size:11px'>`);
  p.push(`  <div style='display:flex;align-items:center;gap:6px'><span>✅</span><span class='chip bl' style='font-size:9px'>tool result</span><span style='color:var(--t3);margin-left:auto'>00:49:27</span></div>`);
  p.push(`  <div style='color:var(--t3);margin-top:3px'>Tool: exec | Status: completed | Duration: 2090ms</div>`);
  p.push(`</div>`);
  p.push(`<div class='_updating' style='color:var(--t3);font-size:11px;padding:8px;margin-top:6px'>↻ Polling live activities...</div>`);
  p.push(`</div>`);
  p.push(`</div>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-mem>`);
  p.push(`<div class=ph><div class=ptitle>Memory Journal</div><div class=pmeta id=mem-cnt>-</div></div>`);
  p.push(`<div style='display:flex;gap:6px;margin-bottom:12px'><input class=inp id=mem-q placeholder='Search memories...'><button class=btn id=btn-mem-r>&#8635;</button></div>`);
  p.push(`<div id=mem-list></div>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-docs>`);
  p.push(`<div class=ph><div class=ptitle>Documents</div></div>`);
  p.push(`<div style='margin-bottom:12px'><input class=inp id=doc-q placeholder='Search documents...'></div>`);
  p.push(`<table class=doc-table><thead><tr><th>File</th><th>Type</th><th>Description</th></tr></thead><tbody id=doc-list></tbody></table>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-team>`);
  p.push(`<div class=ph><div class=ptitle>Team</div><div class=pmeta>CLAWBOT AGENTS</div></div>`);
  p.push(`<div class=tgrid id=team-grid></div>`);
  p.push(`<div class=divl></div>`);
  p.push(`<div class=ph><div class=ptitle>Mission Statement</div></div>`);
  p.push(`<div style='background:var(--c2);border:1px solid var(--border);border-radius:5px;padding:16px'>`);
  p.push(`<div style='font-size:13px;color:var(--t2);line-height:1.8;font-style:italic' id=mission>Build self-running automation systems. Ship one feature daily. Find revenue opportunities. Operate as a solo Batman - nocturnal, precise, relentless. NOW WITH CLAUDE.</div>`);
  p.push(`<button class=btn style='margin-top:12px' id=btn-mission>Edit Mission</button>`);
  p.push(`</div></div>`);
  p.push(`<div class=page id=page-ollama>`);
  p.push(`<div class=ph><div class=ptitle>Ollama</div><div class=pmeta>LOCAL MODELS - :11434</div></div>`);
  p.push(`<div class=mrow style='grid-template-columns:repeat(4,1fr)'>`);
  p.push(`<div class=met><div class='mval gr' id=ol-status-val>-</div><div class=mlbl>Status</div></div>`);
  p.push(`<div class=met><div class='mval yn' id=ol-models-val>-</div><div class=mlbl>Models Loaded</div></div>`);
  p.push(`<div class=met><div class='mval bl'>M4 Pro</div><div class=mlbl>Hardware</div><div class=msub>48GB RAM</div></div>`);
  p.push(`<div class=met><div class='mval gr'>100%</div><div class=mlbl>Private</div><div class=msub>no cloud</div></div>`);
  p.push(`</div>`);
  p.push(`<div class=ollama-box>`);
  p.push(`<div class=ollama-h><span class=ollama-ht>Installed Models</span><span class='chip gr' id=ol-count-chip>loading...</span></div>`);
  p.push(`<div id=ollama-models><div class=empty>Loading Ollama models...</div></div>`);
  p.push(`</div>`);
  p.push(`<div class=divl></div>`);
  p.push(`<div class=ph><div class=ptitle>Usage Guide</div></div>`);
  p.push(`<table class=doc-table><thead><tr><th>Model</th><th>Best For</th><th>Size</th><th>Speed</th></tr></thead>`);
  p.push(`<tbody><tr><td><strong>qwen2.5:32b-instruct</strong></td><td>Complex reasoning, coding</td><td>19GB</td><td><span class='chip yn'>medium</span></td></tr>`);
  p.push(`<tr><td><strong>qwen2.5:14b-instruct</strong></td><td>Fast chat, simple tasks</td><td>9GB</td><td><span class='chip gr'>fast</span></td></tr></tbody></table>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-office>`);
  p.push(`<div class=ph><div class=ptitle>Office View</div><div class=pmeta>2D PIXEL ART</div></div>`);
  p.push(`<div class=offc><canvas id=cv width=640 height=360></canvas><div class=legend id=legend></div></div>`);
  p.push(`</div>`);
  p.push(`<div class=page id=page-models>`);
  p.push(`<div class=ph><div class=ptitle>Model Stack</div><div class=pmeta>M4 PRO 48GB</div></div>`);
  p.push(`<table class=mod-table><thead><tr><th>#</th><th>Model</th><th>Provider</th><th>Cost</th><th>Context</th><th>Status</th></tr></thead>`);
  p.push(`<tbody id=models-list></tbody></table>`);
  p.push(`</div>`);
  p.push(`</div></div></div>`);
  p.push(`<div class=overlay id=overlay><div class=modal><div class=modal-t id=modal-title>New Task</div><div id=modal-body></div><div class=mact><button class=btn id=btn-cancel>Cancel</button><button class='btn yn' id=btn-save>Save</button></div></div></div>`);
  p.push(`<script>`);
  p.push(`var ST = {`);
  p.push(`  sessions:[], cron:[], memory:[], olModels:[], calOff:0, modalType:'',`);
  p.push(`  tasks: JSON.parse(localStorage.getItem('sk_tasks')||'[]'),`);
  p.push(`  projects: JSON.parse(localStorage.getItem('sk_projs')||'null') || [`);
  p.push(`    {id:'p1',name:'OpenClaw JARVIS',icon:'&#129302;',desc:'Full AI stack on M4 Pro. Telegram, briefs, memory.',color:'#f0b90b',prog:65,tasks:8,done:5,status:'active'},`);
  p.push(`    {id:'p2',name:'Revenue Automation',icon:'&#128176;',desc:'Crypto, content, client automation workflows.',color:'#0ecb81',prog:30,tasks:12,done:4,status:'active'},`);
  p.push(`    {id:'p3',name:'Self-Running Systems',icon:'&#9889;',desc:'Pipelines and agents that run without manual input.',color:'#1677ff',prog:45,tasks:6,done:3,status:'active'}`);
  p.push(`  ]`);
  p.push(`};`);
  p.push(`var LABELS={board:'Taskboard',cal:'Calendar',proj:'Projects',ai:'AI Extensions',live:'Live Activity',mem:'Memory',docs:'Documents',team:'Team',ollama:'Ollama',office:'Office',models:'Models'};`);
  p.push(`function goPage(p){`);
  p.push(`  console.log('[goPage]', p);`);
  p.push(`  document.querySelectorAll('.page').forEach(function(el){el.classList.remove('show');});`);
  p.push(`  document.querySelectorAll('.nav[data-p]').forEach(function(el){el.classList.remove('active');});`);
  p.push(`  var pg=document.getElementById('page-'+p);`);
  p.push(`  console.log('[goPage] found page:', !!pg, 'id:', 'page-'+p);`);
  p.push(`  if(pg) { pg.classList.add('show'); console.log('[goPage] added show class'); }`);
  p.push(`  var nav=document.querySelector('.nav[data-p="'+p+'"]');`);
  p.push(`  if(nav) nav.classList.add('active');`);
  p.push(`  var titleEl = document.getElementById('ptitle');`);
  p.push(`  if(titleEl) titleEl.textContent=LABELS[p]||p;`);
  p.push(`  if(p==='cal') renderCal();`);
  p.push(`  if(p==='mem') loadMem();`);
  p.push(`  if(p==='docs') renderDocs();`);
  p.push(`  if(p==='office') drawOffice();`);
  p.push(`  if(p==='team') renderTeam();`);
  p.push(`  if(p==='models') renderModels();`);
  p.push(`  if(p==='ai') renderAI();`);
  p.push(`  if(p==='proj') renderProjects();`);
  p.push(`  if(p==='ollama') renderOllama();`);
  p.push(`  if(p==='live') { console.log('[goPage] calling connectLive'); connectLive(); }`);
  p.push(`}`);
  p.push(`document.querySelectorAll('.nav[data-p]').forEach(function(el){`);
  p.push(`  el.addEventListener('click',function(e){console.log('[nav-click]', el.getAttribute('data-p')); e.preventDefault(); goPage(el.getAttribute('data-p'));});`);
  p.push(`});`);
  p.push(`document.querySelectorAll('.nav[data-a]').forEach(function(el){`);
  p.push(`  el.addEventListener('click',function(e){e.preventDefault(); doAction(el.getAttribute('data-a'));});`);
  p.push(`});`);
  p.push(`document.getElementById('btn-rf').addEventListener('click',refresh);`);
  p.push(`document.getElementById('btn-new').addEventListener('click',function(){openModal('task');});`);
  p.push(`document.getElementById('btn-proj').addEventListener('click',function(){openModal('proj');});`);
  p.push(`document.getElementById('btn-cancel').addEventListener('click',closeModal);`);
  p.push(`document.getElementById('btn-save').addEventListener('click',saveModal);`);
  p.push(`document.getElementById('btn-mem-r').addEventListener('click',loadMem);`);
  p.push(`document.getElementById('btn-mission').addEventListener('click',function(){openModal('mission');});`);
  p.push(`document.getElementById('cal-prev').addEventListener('click',function(){ST.calOff--;renderCal();});`);
  p.push(`document.getElementById('cal-next').addEventListener('click',function(){ST.calOff++;renderCal();});`);
  p.push(`document.getElementById('overlay').addEventListener('click',function(e){if(e.target===this)closeModal();});`);
  p.push(`document.getElementById('mem-q').addEventListener('input',function(){`);
  p.push(`  var q=this.value.toLowerCase();`);
  p.push(`  renderMem(ST.memory.filter(function(m){return m.file.toLowerCase().indexOf(q)>=0||m.preview.toLowerCase().indexOf(q)>=0;}));`);
  p.push(`});`);
  p.push(`document.getElementById('doc-q').addEventListener('input',renderDocs);`);
  p.push(`function feed(msg,type){`);
  p.push(`  var el=document.getElementById('feed');`);
  p.push(`  var t=new Date().toTimeString().slice(0,8);`);
  p.push(`  var d=document.createElement('div'); d.className='fl';`);
  p.push(`  d.innerHTML='<span class="ft">'+t+'</span><span class="fm '+(type||'')+'">'+msg+'</span>';`);
  p.push(`  el.appendChild(d); el.scrollTop=el.scrollHeight;`);
  p.push(`  while(el.children.length>120) el.removeChild(el.firstChild);`);
  p.push(`}`);
  p.push(`function mkCard(id,name,chips,age,pct){`);
  p.push(`  var p=Math.min(pct||0,100),bc=p>80?'ro':p>55?'yn':'';`);
  p.push(`  var ch=(chips||[]).map(function(c){return '<span class="chip '+c.c+'">'+c.l+'</span>';}).join('');`);
  p.push(`  return '<div class="tc"><div class="tc-id">'+id+'</div><div class="tc-name">'+name+'</div><div class="tc-bot"><div class="tc-chips">'+ch+'</div><div class="tc-age">'+(age||'')+'</div></div>'+(p>0?'<div class="tbar"><div class="tbf '+bc+'" style="width:'+p+'%"></div></div>':'')+'</div>';`);
  p.push(`}`);
  p.push(`async function api(path){`);
  p.push(`  try{var r=await fetch(path);return await r.json();}catch(e){return null;}`);
  p.push(`}`);
  p.push(`async function refresh(){`);
  p.push(`  feed('Polling OpenClaw...','info');`);
  p.push(`  var status=await api('/api/status');`);
  p.push(`  var ok=status&&status.ok;`);
  p.push(`  document.getElementById('gwdot').className='dot '+(ok?'on':'off');`);
  p.push(`  document.getElementById('gwtxt').innerHTML='<span class="dot '+(ok?'on':'off')+'"></span>'+(ok?'<span class="stat-val on">ONLINE</span>':'<span class="stat-val off">OFFLINE</span>');`);
  p.push(`  document.getElementById('m-gw-val').textContent=ok?'OK':'OFF';`);
  p.push(`  document.getElementById('m-gw-val').className='mval '+(ok?'gr':'ro');`);
  p.push(`  document.getElementById('m-gw').textContent=ok?'port 8188':'offline';`);
  p.push(`  document.getElementById('tk-gw').textContent=ok?'ONLINE':'OFFLINE';`);
  p.push(`  document.getElementById('tk-gw').style.color=ok?'var(--gr)':'var(--ro)';`);
  p.push(`  if(ok) feed('Gateway reachable','ok'); else feed('Gateway offline','warn');`);
  p.push(`  var sess=await api('/api/sessions'); ST.sessions=(sess&&sess.sessions)||[];`);
  p.push(`  document.getElementById('m-sess').textContent=ST.sessions.length||'0';`);
  p.push(`  document.getElementById('nb-b').textContent=ST.sessions.length||'0';`);
  p.push(`  document.getElementById('tk-sess').textContent=ST.sessions.length+' ACTIVE';`);
  p.push(`  var cron=await api('/api/cron'); ST.cron=(cron&&cron.jobs)||[];`);
  p.push(`  document.getElementById('m-cron').textContent=ST.cron.length||2;`);
  p.push(`  document.getElementById('tk-cron').textContent=(ST.cron.length||2)+' JOBS';`);
  p.push(`  var avg=ST.sessions.length?Math.round(ST.sessions.reduce(function(a,s){return a+(s.tokenPct||0);},0)/ST.sessions.length):0;`);
  p.push(`  document.getElementById('m-tok').textContent=avg?avg+'%':'-';`);
  p.push(`  var ol=await api('/api/ollama');`);
  p.push(`  if(ol&&ol.ok){`);
  p.push(`    ST.olModels=(ol.models)||[];`);
  p.push(`    document.getElementById('oldot').className='dot yn';`);
  p.push(`    document.getElementById('oltxt').innerHTML='<span class="dot yn"></span><span class="stat-val yn">'+ST.olModels.length+' MODELS</span>';`);
  p.push(`    document.getElementById('m-ol-val').textContent=ST.olModels.length;`);
  p.push(`    document.getElementById('m-ol-val').className='mval yn';`);
  p.push(`    document.getElementById('m-ol-sub').textContent=ST.olModels.length+' models';`);
  p.push(`    document.getElementById('nb-ol').textContent=ST.olModels.length;`);
  p.push(`    document.getElementById('tk-ol').textContent=ST.olModels.length+' MODELS';`);
  p.push(`    document.getElementById('tk-ol').style.color='var(--yn)';`);
  p.push(`  } else {`);
  p.push(`    document.getElementById('oldot').className='dot off';`);
  p.push(`    document.getElementById('oltxt').innerHTML='<span class="dot off"></span><span class="stat-val off">OFFLINE</span>';`);
  p.push(`    document.getElementById('m-ol-val').textContent='OFF';`);
  p.push(`    document.getElementById('m-ol-val').className='mval ro';`);
  p.push(`    document.getElementById('tk-ol').textContent='OFFLINE';`);
  p.push(`    document.getElementById('tk-ol').style.color='var(--ro)';`);
  p.push(`  }`);
  p.push(`  var tg=ST.sessions.filter(function(s){return (s.key||'').indexOf('telegram')>=0;});`);
  p.push(`  document.getElementById('tk-tg').textContent=tg.length?tg.length+' ACTIVE':'IDLE';`);
  p.push(`  renderBoard();`);
  p.push(`  if(ST.sessions.length) feed(ST.sessions.length+' sessions loaded','ok');`);
  p.push(`}`);
  p.push(`function renderBoard(){`);
  p.push(`  var ss=ST.sessions;`);
  p.push(`  document.getElementById('c0').textContent=ss.length;`);
  p.push(`  document.getElementById('col0').innerHTML=ss.length?ss.slice(0,6).map(function(s){`);
  p.push(`    var chips=[];`);
  p.push(`    if((s.key||'').indexOf('telegram')>=0) chips.push({c:'gr',l:'tg'});`);
  p.push(`    if((s.key||'').indexOf('cron')>=0) chips.push({c:'yn',l:'cron'});`);
  p.push(`    chips.push({c:'bl',l:(s.model||'').split('/').pop().slice(0,8)});`);
  p.push(`    return mkCard((s.key||'').replace('agent:main:','').slice(0,14),(s.key||'').replace('agent:main:',''),chips,s.age+'ago',s.tokenPct||0);`);
  p.push(`  }).join(''):'<div class="empty"><div class="empty-i">&#128172;</div>No active sessions</div>';`);
  p.push(`  var tg=ss.filter(function(s){return (s.key||'').indexOf('telegram')>=0;});`);
  p.push(`  document.getElementById('c1').textContent=tg.length;`);
  p.push(`  document.getElementById('col1').innerHTML=tg.length?tg.map(function(s){return mkCard('tg','Telegram - '+(s.model||''),[{c:'gr',l:'live'},{c:'bl',l:'active'}],s.age+'ago',s.tokenPct||0);}).join(''):'<div class="empty"><div class="empty-i">&#9992;</div>No active chats</div>';`);
  p.push(`  document.getElementById('c2').textContent=ST.cron.length;`);
  p.push(`  document.getElementById('col2').innerHTML=ST.cron.length?ST.cron.map(function(j){return mkCard(j.id.slice(0,8),j.name,[{c:'yn',l:'cron'},{c:j.status==='ok'?'gr':'ro',l:j.status||'idle'}],'next '+j.next,0);}).join(''):'<div class="empty"><div class="empty-i">&#8987;</div>No jobs</div>';`);
  p.push(`  if(ST.tasks.length){var c3=document.getElementById('col3'),ex=c3.innerHTML;c3.innerHTML=ST.tasks.map(function(t){return mkCard(t.id,t.name,[{c:'bl',l:t.status}],t.created,0);}).join('')+ex;document.getElementById('c3').textContent=ST.tasks.length+2;}`);
  p.push(`}`);
  p.push(`var CDAYS=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];`);
  p.push(`var CMONS=['January','February','March','April','May','June','July','August','September','October','November','December'];`);
  p.push(`function renderCal(){`);
  p.push(`  var now=new Date(),d=new Date(now.getFullYear(),now.getMonth()+ST.calOff,1);`);
  p.push(`  var y=d.getFullYear(),m=d.getMonth();`);
  p.push(`  document.getElementById('cal-title').textContent=CMONS[m]+' '+y;`);
  p.push(`  document.getElementById('cal-hd').innerHTML=CDAYS.map(function(x){return '<div class="calhd">'+x+'</div>';}).join('');`);
  p.push(`  var first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();`);
  p.push(`  var html='';`);
  p.push(`  for(var i=0;i<first;i++) html+='<div class="calday faded"><div class="caldn">'+(prev-first+1+i)+'</div></div>';`);
  p.push(`  for(var dd=1;dd<=last;dd++){`);
  p.push(`    var iT=dd===now.getDate()&&m===now.getMonth()&&y===now.getFullYear()&&ST.calOff===0;`);
  p.push(`    html+='<div class="calday'+(iT?' today':'')+'"><div class="caldn">'+dd+'</div>'+(iT?'<div class="calev yn">08:00 Brief</div><div class="calev gr">20:00 Summary</div>':'')+'</div>';`);
  p.push(`  }`);
  p.push(`  document.getElementById('cal-body').innerHTML=html;`);
  p.push(`}`);
  p.push(`function renderProjects(){`);
  p.push(`  document.getElementById('nb-p').textContent=ST.projects.length;`);
  p.push(`  document.getElementById('proj-grid').innerHTML=ST.projects.map(function(p){`);
  p.push(`    return '<div class="pj" data-pid="'+p.id+'"><div class="pj-top"><div class="pj-ico" style="background:'+p.color+'22">'+p.icon+'</div><span class="chip '+(p.status==='active'?'gr':'yn')+'">'+p.status+'</span></div><div class="pj-name">'+p.name+'</div><div class="pj-desc">'+p.desc+'</div><div class="pbar"><div class="pfill" style="width:'+p.prog+'%;background:'+p.color+'"></div></div><div class="plbl"><span>'+p.done+'/'+p.tasks+' tasks</span><span>'+p.prog+'%</span></div></div>';`);
  p.push(`  }).join('')+'<div class="addbox" id="add-proj-btn"><div style="font-size:22px;margin-bottom:4px">+</div>New Project</div>';`);
  p.push(`  document.querySelectorAll('.pj[data-pid]').forEach(function(el){`);
  p.push(`    el.addEventListener('click',function(){var p=ST.projects.find(function(x){return x.id===el.dataset.pid;});if(p) alert(p.name+'\\n\\n'+p.desc+'\\n\\nProgress: '+p.prog+'%');});`);
  p.push(`  });`);
  p.push(`  var ab=document.getElementById('add-proj-btn'); if(ab) ab.addEventListener('click',function(){openModal('proj');});`);
  p.push(`}`);
  p.push(`function renderAI(){`);
  p.push(`  var sugs=[{icon:'&#128273;',text:'Rotate OpenAI API key - exposed in chat history',cat:'SECURITY'},{icon:'&#128176;',text:'Daily crypto alert cron for BTC + ETH at 9am',cat:'AUTOMATION'},{icon:'&#128225;',text:'Get Brave Search API key for better web search',cat:'TOOLS'},{icon:'&#129302;',text:'Add Claude Sonnet after Anthropic org recovery',cat:'SYSTEM'},{icon:'&#128221;',text:'Write standup template and add to morning brief',cat:'PRODUCTIVITY'},{icon:'&#128161;',text:'Revenue Automation at 30% - needs 3 more tasks',cat:'PRIORITY'}];`);
  p.push(`  document.getElementById('ai-sugs').innerHTML=sugs.map(function(s){return '<div class="airow" data-task="'+s.text.replace(/"/g,'')+'"><div class="ai-ico">'+s.icon+'</div><div><div class="ai-txt">'+s.text+'</div><div class="ai-sub">'+s.cat+' &bull; click to add to board</div></div></div>';}).join('');`);
  p.push(`  document.querySelectorAll('#ai-sugs .airow').forEach(function(el){el.addEventListener('click',function(){addFromAI(el.dataset.task);});});`);
  p.push(`  document.getElementById('ai-focus').innerHTML=[{t:'Revenue Automation',s:'30%',c:'yn'},{t:'OpenClaw JARVIS',s:'65%',c:'gr'},{t:'API Key Rotation',s:'critical',c:'ro'}].map(function(f){return '<div class="airow" style="margin-bottom:4px"><div class="ai-txt">'+f.t+'</div><div class="ai-sub"><span class="chip '+f.c+'">'+f.s+'</span></div></div>';}).join('');`);
  p.push(`  document.getElementById('ai-cats').innerHTML=[{l:'Automation',n:8,c:'bl'},{l:'Revenue',n:5,c:'gr'},{l:'Security',n:2,c:'ro'},{l:'Learning',n:3,c:'yn'}].map(function(c){return '<div class="airow" style="margin-bottom:4px;justify-content:space-between;align-items:center"><span class="ai-txt">'+c.l+'</span><span class="chip '+c.c+'">'+c.n+'</span></div>';}).join('');`);
  p.push(`}`);
  p.push(`function addFromAI(text){`);
  p.push(`  var t={id:'AI-'+Date.now().toString(36).slice(-4),name:text,status:'todo',created:new Date().toLocaleDateString()};`);
  p.push(`  ST.tasks.unshift(t); localStorage.setItem('sk_tasks',JSON.stringify(ST.tasks));`);
  p.push(`  feed('AI task added: '+text.slice(0,40)+'...','ok'); goPage('board');`);
  p.push(`}`);
  p.push(`async function loadMem(){`);
  p.push(`  document.getElementById('mem-list').innerHTML='<div class="empty">Loading...</div>';`);
  p.push(`  var r=await api('/api/memory'); ST.memory=(r&&r.files)||[];`);
  p.push(`  document.getElementById('mem-cnt').textContent=ST.memory.length+' files';`);
  p.push(`  document.getElementById('nb-m').textContent=ST.memory.length||'-';`);
  p.push(`  renderMem(ST.memory);`);
  p.push(`}`);
  p.push(`function renderMem(items){`);
  p.push(`  if(!items.length){document.getElementById('mem-list').innerHTML='<div class="empty"><div class="empty-i">&#129504;</div>No memory files</div>';return;}`);
  p.push(`  document.getElementById('mem-list').innerHTML=items.map(function(f){return '<div class="memcard"><div class="memfile">'+f.file+'</div><div class="memprev">'+f.preview.slice(0,300).replace(/</g,'&lt;')+(f.preview.length>300?'...':'')+'</div><div class="memmeta">'+f.lines+' lines - '+f.size+' chars</div></div>';}).join('');`);
  p.push(`}`);
  p.push(`var DOCS=[{name:'IDENTITY.md',type:'config',meta:'Agent identity and persona'},{name:'SOUL.md',type:'config',meta:'Agent values and behavior'},{name:'USER.md',type:'profile',meta:'User: Skele, Myawaddy, Myanmar'},{name:'MEMORY.md',type:'memory',meta:'Persistent memory and context'},{name:'AGENTS.md',type:'system',meta:'Agent configuration'},{name:'HEARTBEAT.md',type:'system',meta:'Heartbeat monitoring'},{name:'yt-caption.sh',type:'script',meta:'YouTube subtitle extractor'}];`);
  p.push(`var TCHIP={config:'yn',profile:'gr',memory:'bl',system:'pu',script:'ro'};`);
  p.push(`function renderDocs(){`);
  p.push(`  var q=(document.getElementById('doc-q').value||'').toLowerCase();`);
  p.push(`  var items=DOCS.filter(function(d){return !q||d.name.toLowerCase().indexOf(q)>=0||d.meta.toLowerCase().indexOf(q)>=0;});`);
  p.push(`  document.getElementById('doc-list').innerHTML=items.map(function(d){return '<tr><td><strong>'+d.name+'</strong></td><td><span class="chip '+(TCHIP[d.type]||'bl')+'">'+d.type+'</span></td><td style="color:var(--t2)">'+d.meta+'</td></tr>';}).join('');`);
  p.push(`}`);
  p.push(`function renderOllama(){`);
  p.push(`  var box=document.getElementById('ollama-models');`);
  p.push(`  if(!ST.olModels||!ST.olModels.length){`);
  p.push(`    box.innerHTML='<div class="empty"><div class="empty-i">&#129422;</div>Ollama offline or no models. Run: ollama pull qwen2.5:32b-instruct</div>';`);
  p.push(`    document.getElementById('ol-status-val').textContent='OFF';`);
  p.push(`    document.getElementById('ol-status-val').className='mval ro';`);
  p.push(`    document.getElementById('ol-models-val').textContent='0';`);
  p.push(`    document.getElementById('ol-count-chip').textContent='offline';`);
  p.push(`    document.getElementById('ol-count-chip').className='chip ro';`);
  p.push(`    return;`);
  p.push(`  }`);
  p.push(`  document.getElementById('ol-status-val').textContent='ON';`);
  p.push(`  document.getElementById('ol-status-val').className='mval gr';`);
  p.push(`  document.getElementById('ol-models-val').textContent=ST.olModels.length;`);
  p.push(`  document.getElementById('ol-count-chip').textContent=ST.olModels.length+' models';`);
  p.push(`  document.getElementById('ol-count-chip').className='chip gr';`);
  p.push(`  box.innerHTML=ST.olModels.map(function(m){`);
  p.push(`    var gb=m.size?((m.size/1e9).toFixed(1)+'GB'):'?GB';`);
  p.push(`    var name=m.name||m.model||'unknown';`);
  p.push(`    var isActive=name.indexOf('32b')>=0||name.indexOf('14b')>=0;`);
  p.push(`    return '<div class="ollama-row"><div class="ol-name">'+name+'</div><div class="ol-size">'+gb+'</div><span class="chip '+(isActive?'gr':'gr2')+'">'+( isActive?'active':'loaded')+'</span></div>';`);
  p.push(`  }).join('');`);
  p.push(`}`);
  p.push(`function renderTeam(){`);
  p.push(`  var agents=[{name:'Skele',role:'BATMAN OPERATOR',av:'&#129415;',col:'var(--yn)',task:'Running Mission Control, building automation stack',c:'yn',me:true},{name:'Ski (main)',role:'PRIMARY AGENT',av:'S',col:'var(--gr)',task:'Telegram bot, web search, tool execution',c:'gr'},{name:'Cron Agent',role:'SCHEDULER',av:'&#9200;',col:'var(--yn)',task:'morning-brief 08:00, day-summary 20:00 MMT',c:'yn'},{name:'GPT-4o',role:'TOOL EXECUTOR',av:'G',col:'#10b981',task:'Web fetch, image analysis, primary model',c:'gr'},{name:'Groq 70b',role:'FAST CHAT',av:'&#9889;',col:'var(--yn)',task:'Simple chat, free tier, no tools',c:'yn'},{name:'Claude Sonnet',role:'PRIMARY AGENT',av:'C',col:'var(--pu)',task:'claude-sonnet-4-5 via ANTHROPIC_API_KEY - active',c:'gr'}];`);
  p.push(`  document.getElementById('team-grid').innerHTML=agents.map(function(a){return '<div class="agcard'+(a.me?' me':'')+'"><div class="ag-top"><div class="ag-av" style="background:'+a.col+'22">'+a.av+'</div><div><div class="ag-name">'+a.name+'</div><div class="ag-role">'+a.role+'</div></div></div><div class="ag-task">'+a.task+'</div><span class="chip '+a.c+'">'+(a.me?'operator':a.c==='gr'?'active':a.c==='yn'?'idle':'pending')+'</span></div>';}).join('');`);
  p.push(`}`);
  p.push(`function renderModels(){`);
  p.push(`  var list=[{r:'02',n:'GPT-4o',prov:'OpenAI',desc:'Tool execution, web fetch, image analysis - fallback',cost:'~$0.005/msg',ctx:'128k',c:'gr'},{r:'02',n:'Groq Llama 3.3 70b',prov:'Groq',desc:'Fastest chat, free tier, no tools',cost:'FREE',ctx:'131k',c:'gr'},{r:'03',n:'Qwen 2.5 32b',prov:'Ollama Local',desc:'M4 Pro GPU, 19GB, 100% private',cost:'FREE',ctx:'32k',c:'yn'},{r:'04',n:'Qwen 2.5 14b',prov:'Ollama Local',desc:'Lighter fallback, 9GB',cost:'FREE',ctx:'16k',c:'yn'},{r:'01',n:'Claude Sonnet 4.5',prov:'Anthropic',desc:'Primary model - claude-sonnet-4-5 - best reasoning',cost:'~$0.003/msg',ctx:'200k',c:'pu',pri:true}];`);
  p.push(`  document.getElementById('models-list').innerHTML=list.map(function(m){return '<tr><td style="font-family:IBM Plex Mono,monospace;font-size:11px;color:var(--t3)">'+m.r+'</td><td><div class="mod-name">'+m.n+(m.pri?' <span class="chip gr">PRIMARY</span>':'')+'</div><div class="mod-desc">'+m.desc+'</div></td><td><span class="chip '+m.c+'">'+m.prov+'</span></td><td class="mod-cost">'+m.cost+'</td><td class="mod-ctx">'+m.ctx+'</td><td><span class="chip '+(m.pri?'gr':m.c==='ro'?'ro':'gr2')+'">'+( m.pri?'active':m.c==='ro'?'pending':'loaded')+'</span></td></tr>';}).join('');`);
  p.push(`}`);
  p.push(`function drawOffice(){`);
  p.push(`  var cv=document.getElementById('cv'),ctx=cv.getContext('2d');`);
  p.push(`  var W=640,H=360,T=16;`);
  p.push(`  ctx.fillStyle='#0b0e11'; ctx.fillRect(0,0,W,H);`);
  p.push(`  for(var x=0;x<W;x+=T) for(var y=H-T*4;y<H;y+=T){ctx.fillStyle=(Math.floor(x/T)+Math.floor(y/T))%2===0?'#0f1217':'#0b0e11';ctx.fillRect(x,y,T,T);}`);
  p.push(`  ctx.fillStyle='#0d1117'; ctx.fillRect(0,0,W,H-T*4);`);
  p.push(`  ctx.strokeStyle='rgba(255,255,255,0.02)'; ctx.lineWidth=1;`);
  p.push(`  for(var gx=0;gx<W;gx+=T*4){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,H-T*4);ctx.stroke();}`);
  p.push(`  for(var gy=0;gy<H-T*4;gy+=T*4){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(W,gy);ctx.stroke();}`);
  p.push(`  [[60,30],[200,30],[360,30],[500,30]].forEach(function(w){ctx.fillStyle='#0d1520';ctx.fillRect(w[0],w[1],T*4,T*5);ctx.strokeStyle='#1a2535';ctx.lineWidth=1;ctx.strokeRect(w[0],w[1],T*4,T*5);});`);
  p.push(`  var desks=[{x:50,y:H-T*10,label:'Skele',active:true,col:'#1a1800'},{x:200,y:H-T*10,label:'Ski',active:true,col:'#001a10'},{x:350,y:H-T*10,label:'Cron',active:false,col:'#141820'},{x:500,y:H-T*10,label:'Claude',active:false,col:'#1a1420'}];`);
  p.push(`  desks.forEach(function(d){`);
  p.push(`    ctx.fillStyle=d.col; ctx.fillRect(d.x,d.y,T*6,T*3);`);
  p.push(`    ctx.strokeStyle=d.active?'rgba(240,185,11,0.4)':'rgba(255,255,255,0.05)'; ctx.lineWidth=1; ctx.strokeRect(d.x,d.y,T*6,T*3);`);
  p.push(`    ctx.fillStyle='#0b0e11'; ctx.fillRect(d.x+T,d.y-T*3,T*4,T*3);`);
  p.push(`    if(d.active){ctx.fillStyle=d.label==='Skele'?'rgba(240,185,11,0.2)':'rgba(14,203,129,0.2)';ctx.fillRect(d.x+T+1,d.y-T*3+1,T*4-2,T*3-2);}`);
  p.push(`    ctx.strokeStyle=d.active?'rgba(240,185,11,0.5)':'rgba(255,255,255,0.06)'; ctx.strokeRect(d.x+T,d.y-T*3,T*4,T*3);`);
  p.push(`    if(d.active){ctx.fillStyle=d.label==='Skele'?'#f0b90b':'#0ecb81';ctx.fillRect(d.x+T*2+2,d.y+T+4,T-2,T-2);ctx.fillStyle='#fde68a';ctx.fillRect(d.x+T*2+4,d.y+T-4,8,8);}`);
  p.push(`    ctx.font='10px IBM Plex Mono,monospace'; ctx.textAlign='center';`);
  p.push(`    ctx.fillStyle=d.active?(d.label==='Skele'?'rgba(240,185,11,0.9)':'rgba(14,203,129,0.9)'):'rgba(255,255,255,0.2)';`);
  p.push(`    ctx.fillText(d.label,d.x+T*3,d.y+T*6+4);`);
  p.push(`  });`);
  p.push(`  document.getElementById('legend').innerHTML=desks.map(function(d){return '<div class="leg"><div class="leg-d" style="background:'+(d.active?d.label==='Skele'?'#f0b90b':'#0ecb81':'#2b3139')+'></div>'+d.label+'</div>';}).join('');`);
  p.push(`}`);
  p.push(`function openModal(type){`);
  p.push(`  ST.modalType=type;`);
  p.push(`  var titles={task:'New Task',proj:'New Project',mission:'Edit Mission'};`);
  p.push(`  document.getElementById('modal-title').textContent=titles[type]||'New';`);
  p.push(`  var forms={task:'<div class="mrow2"><div class="mlbl">Task Name</div><input class="inp" id="mi0" placeholder="What needs to be done?"></div><div class="mrow2"><div class="mlbl">Status</div><input class="inp" id="mi1" placeholder="todo / in-progress / done" value="todo"></div>',proj:'<div class="mrow2"><div class="mlbl">Project Name</div><input class="inp" id="mi0" placeholder="Project name"></div><div class="mrow2"><div class="mlbl">Description</div><input class="inp" id="mi1" placeholder="What is this project about?"></div>',mission:'<div class="mrow2"><div class="mlbl">Mission Statement</div><textarea class="inp" id="mi0" rows="4">'+document.getElementById('mission').textContent.trim()+'</textarea></div>'};`);
  p.push(`  document.getElementById('modal-body').innerHTML=forms[type]||'';`);
  p.push(`  document.getElementById('overlay').classList.add('open');`);
  p.push(`  setTimeout(function(){var el=document.getElementById('mi0');if(el)el.focus();},60);`);
  p.push(`}`);
  p.push(`function closeModal(){document.getElementById('overlay').classList.remove('open');}`);
  p.push(`function saveModal(){`);
  p.push(`  var el0=document.getElementById('mi0'),v0=el0&&el0.value.trim();`);
  p.push(`  var el1=document.getElementById('mi1'),v1=el1&&el1.value.trim()||'';`);
  p.push(`  if(!v0) return;`);
  p.push(`  if(ST.modalType==='task'){ST.tasks.unshift({id:'T-'+Date.now().toString(36).slice(-4),name:v0,status:v1||'todo',created:new Date().toLocaleDateString()});localStorage.setItem('sk_tasks',JSON.stringify(ST.tasks));renderBoard();feed('Task created: '+v0,'ok');}`);
  p.push(`  else if(ST.modalType==='proj'){var cols=['#f0b90b','#0ecb81','#1677ff','#f6465d','#c084fc'];ST.projects.push({id:'p'+Date.now(),name:v0,icon:'&#128204;',desc:v1,color:cols[ST.projects.length%cols.length],prog:0,tasks:0,done:0,status:'active'});localStorage.setItem('sk_projs',JSON.stringify(ST.projects));renderProjects();feed('Project: '+v0,'ok');}`);
  p.push(`  else if(ST.modalType==='mission'){document.getElementById('mission').textContent=v0;feed('Mission updated','ok');}`);
  p.push(`  closeModal();`);
  p.push(`}`);
  p.push(`function doAction(cmd){`);
  p.push(`  var cmds={restart:'openclaw gateway install --force && openclaw gateway restart',brief:'openclaw cron run 63f7ed9a-0fff-4caf-89e4-4bf8f58298b7',clear:'rm ~/.openclaw/agents/main/sessions/*.jsonl && openclaw gateway restart'};`);
  p.push(`  var t=cmds[cmd]; feed('Run: '+t,'info');`);
  p.push(`  if(navigator.clipboard) navigator.clipboard.writeText(t).then(function(){feed('Copied!','ok');}).catch(function(){});`);
  p.push(`}`);
  p.push(`function tick(){`);
  p.push(`  var s=new Date().toTimeString().slice(0,8);`);
  p.push(`  document.getElementById('clk').textContent=s+' MMT';`);
  p.push(`}`);
  p.push(`setTimeout(function(){feed('Ski Mission Control v4 - Claude Edition','info');},100);`);
  p.push(`setTimeout(function(){feed('Connecting to OpenClaw + Ollama...','info');},400);`);
  p.push(`setTimeout(function(){refresh();},700);`);
  p.push(`setTimeout(function(){renderDocs();},900);`);
  p.push(`setTimeout(function(){feed('Security: Rotate OpenAI API key!','warn');},3500);`);
  p.push(`setTimeout(function(){feed('Claude Sonnet is PRIMARY. Batman mode active.','ok');},4200);`);
  p.push(`setInterval(tick,1000); setInterval(refresh,15000); tick();`);
  p.push(`var liveStats={acts:0,tools:0,api:0,files:0,errs:0,health:100},liveShown={},liveTimer=null;`);
  p.push(`function connectLive(){`);
  p.push(`  console.log('[connectLive] starting...');`);
  p.push(`  if(liveTimer) { console.log('[connectLive] already running'); return; }`);
  p.push(`  var statusEl=document.getElementById('ws-status');`);
  p.push(`  if(!statusEl) { console.log('[connectLive] no status element'); return; }`);
  p.push(`  statusEl.textContent='Loading...';`);
  p.push(`  statusEl.className='chip yn';`);
  p.push(`  function pollActivities(){`);
  p.push(`    fetch('/api/live-activities?limit=50').then(function(r){`);
  p.push(`      if(!r.ok) throw new Error(r.status);`);
  p.push(`      return r.json();`);
  p.push(`    }).then(function(d){`);
  p.push(`      console.log('[pollActivities] got ' + (d.activities ? d.activities.length : 0) + ' activities');`);
  p.push(`      var statusEl=document.getElementById('ws-status');`);
  p.push(`      if(statusEl){ statusEl.textContent='Live'; statusEl.className='chip gr'; }`);
  p.push(`      if(d.activities && d.activities.length > 0){`);
  p.push(`        d.activities.slice().reverse().forEach(function(a){`);
  p.push(`          var key=a.timestamp+(a.type||'');`);
  p.push(`          if(!liveShown[key]){ liveShown[key]=true; console.log('[renderActivity] ' + a.type); if(renderActivity) renderActivity(a); }`);
  p.push(`        });`);
  p.push(`      }`);
  p.push(`    }).catch(function(e){`);
  p.push(`      console.error('[pollActivities] error:', e);`);
  p.push(`      var statusEl=document.getElementById('ws-status');`);
  p.push(`      if(statusEl){ statusEl.textContent='Error'; statusEl.className='chip ro'; }`);
  p.push(`    });`);
  p.push(`  }`);
  p.push(`  console.log('[connectLive] calling pollActivities first time');`);
  p.push(`  pollActivities();`);
  p.push(`  liveTimer=setInterval(pollActivities,2000);`);
  p.push(`  console.log('[connectLive] started polling interval');`);
  p.push(`}`);
  p.push(`function renderActivity(a){`);
  p.push(`  if(!a||!a.type) return;`);
  p.push(`  var stream=document.getElementById('live-stream');`);
  p.push(`  if(!stream) return;`);
  p.push(`  var loader=stream.querySelector('._sample_loading');`);
  p.push(`  if(loader) loader.remove();`);
  p.push(`  var time=new Date(a.timestamp).toLocaleTimeString();`);
  p.push(`  var typeColors={tool_call:'bl',tool_result:'bl',file_write:'pu',file_edit:'pu',api_usage:'yn',error:'ro',command:'yn',health:'gr',thinking:'gr2',decision:'bl'};`);
  p.push(`  var typeIcons={tool_call:'🔧',tool_result:'✅',file_write:'💾',file_edit:'📝',api_usage:'🌐',error:'❌',command:'⚙️',health:'💚',thinking:'💭',decision:'🎯'};`);
  p.push(`  var icon=typeIcons[a.type]||'•';`);
  p.push(`  var color=typeColors[a.type]||'gr2';`);
  p.push(`  var el=document.createElement('div');`);
  p.push(`  el.style='background:var(--c3);border:1px solid var(--border);border-radius:4px;padding:8px;margin-bottom:6px;font-size:11px;font-family:IBM Plex Mono,monospace';`);
  p.push(`  var details='';`);
  p.push(`  if(a.tool) details='<div style="color:var(--t3);margin-top:3px">Tool: '+a.tool+'</div>';`);
  p.push(`  if(a.status) details+='<div style="color:var(--t3);margin-top:2px">Status: '+a.status+'</div>';`);
  p.push(`  if(a.duration) details+='<div style="color:var(--t3);margin-top:2px">Duration: '+a.duration+'ms</div>';`);
  p.push(`  if(a.model) details+='<div style="color:var(--t3);margin-top:2px">'+a.model+' ('+a.input+'/'+a.output+' tokens, $'+(a.cost||0).toFixed(4))+'</div>';`);
  p.push(`  if(a.command) details+='<div style="color:var(--t3);margin-top:3px">'+a.command.substring(0,80)+'</div>';`);
  p.push(`  el.innerHTML='<div style="display:flex;align-items:center;gap:6px"><span>'+icon+'</span><span class="chip '+color+'" style="font-size:9px">'+a.type.replace(/_/g,' ')+'</span><span style="color:var(--t3);margin-left:auto">'+time+'</span></div>'+details;`);
  p.push(`  stream.insertBefore(el,stream.firstChild);`);
  p.push(`  while(stream.children.length>100) stream.removeChild(stream.lastChild);`);
  p.push(`  liveStats.acts++;`);
  p.push(`  if(a.type==='tool_call') liveStats.tools++;`);
  p.push(`  if(a.type==='api_usage') liveStats.api++;`);
  p.push(`  if(a.type==='file_write'||a.type==='file_edit') liveStats.files++;`);
  p.push(`  if(a.type==='error') liveStats.errs++;`);
  p.push(`  var actEl=document.getElementById('live-acts');`);
  p.push(`  if(actEl) actEl.textContent=liveStats.acts;`);
  p.push(`  var toolsEl=document.getElementById('live-tools');`);
  p.push(`  if(toolsEl) toolsEl.textContent=liveStats.tools;`);
  p.push(`  var apiEl=document.getElementById('live-api');`);
  p.push(`  if(apiEl) apiEl.textContent=liveStats.api;`);
  p.push(`  var filesEl=document.getElementById('live-files');`);
  p.push(`  if(filesEl) filesEl.textContent=liveStats.files;`);
  p.push(`  var errsEl=document.getElementById('live-errs');`);
  p.push(`  if(errsEl) errsEl.textContent=liveStats.errs;`);
  p.push(`  var nbEl=document.getElementById('nb-live');`);
  p.push(`  if(nbEl) nbEl.textContent=liveStats.acts;`);
  p.push(`}`);
  p.push(`function startLivePolling() {`);
  p.push(`  if(liveTimer) return;`);
  p.push(`  console.log('[startLivePolling] initializing...');`);
  p.push(`  function poll() {`);
  p.push(`    fetch('/api/live-activities?limit=50')`);
  p.push(`      .then(r => r.json())`);
  p.push(`      .then(d => {`);
  p.push(`        if(d.activities && d.activities.length > 0) {`);
  p.push(`          d.activities.reverse().forEach(a => {`);
  p.push(`            var key = a.timestamp + a.type;`);
  p.push(`            if(!liveShown[key]) {`);
  p.push(`              liveShown[key] = true;`);
  p.push(`              renderActivity(a);`);
  p.push(`            }`);
  p.push(`          });`);
  p.push(`        }`);
  p.push(`        var statusEl = document.getElementById('ws-status');`);
  p.push(`        if(statusEl) { statusEl.textContent = 'Live'; statusEl.className = 'chip gr'; }`);
  p.push(`      })`);
  p.push(`      .catch(e => console.error('[poll] error:', e));`);
  p.push(`  }`);
  p.push(`  poll();`);
  p.push(`  liveTimer = setInterval(poll, 2000);`);
  p.push(`}`);
  p.push(`if(document.readyState === 'loading') {`);
  p.push(`  document.addEventListener('DOMContentLoaded', startLivePolling);`);
  p.push(`} else {`);
  p.push(`  startLivePolling();`);
  p.push(`}`);
  p.push(`</script>`);
  p.push(`</body></html>`);
  return p.join('\n');
}

const HTML = buildHTML();

const server = http.createServer(async function(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');

  if (req.url.startsWith('/api/live-activities')) {
    var limit = 50;
    var match = req.url.match(/limit=(\d+)/);
    if (match) limit = parseInt(match[1]) || 50;
    try {
      await new Promise(function(resolve) {
        var r = http.get({hostname:'127.0.0.1',port:3132,path:'/api/activities?limit='+limit,timeout:3000},function(res2){
          var d = '';
          res2.on('data',function(c){d+=c;});
          res2.on('end',function(){
            try {
              var data = JSON.parse(d);
              res.writeHead(200,{'Content-Type':'application/json'});
              res.end(JSON.stringify(data));
            } catch(e) {
              res.writeHead(500,{'Content-Type':'application/json'});
              res.end(JSON.stringify({error:'Failed to parse response'}));
            }
            resolve();
          });
        });
        r.on('error',function(){
          res.writeHead(500,{'Content-Type':'application/json'});
          res.end(JSON.stringify({error:'Failed to connect to activity streamer'}));
          resolve();
        });
        r.on('timeout',function(){r.destroy(); res.writeHead(500,{'Content-Type':'application/json'}); res.end(JSON.stringify({error:'Timeout'})); resolve();});
      });
      return;
    } catch(e) {
      res.writeHead(500,{'Content-Type':'application/json'});
      res.end(JSON.stringify({error:e.message}));
      return;
    }
  }

  if (req.url === '/api/status') {
    var ok = false;
    try {
      await new Promise(function(resolve) {
        var r = http.get({hostname:'127.0.0.1',port:8188,path:'/health',timeout:2000,headers:{Authorization:'Bearer ski-local-fresh-001'}},function(res2){ok=res2.statusCode<500;resolve();});
        r.on('error',resolve); r.on('timeout',function(){r.destroy();resolve();});
      });
    } catch(e) {}
    res.writeHead(200,{'Content-Type':'application/json'});
    res.end(JSON.stringify({ok:ok})); return;
  }

  if (req.url === '/api/sessions') {
    res.writeHead(200,{'Content-Type':'application/json'});
    res.end(JSON.stringify({ok:true,sessions:getSessions()})); return;
  }

  if (req.url === '/api/memory') {
    res.writeHead(200,{'Content-Type':'application/json'});
    res.end(JSON.stringify({ok:true,files:getMemory()})); return;
  }

  if (req.url === '/api/cron') {
    res.writeHead(200,{'Content-Type':'application/json'});
    res.end(JSON.stringify({ok:true,jobs:[
      {id:'63f7ed9a',name:'morning-brief-v4',schedule:'0 8 * * *',next:'08:00 MMT',model:'openai/gpt-4o',status:'ok'},
      {id:'8d9d82d2',name:'day-summary',schedule:'0 20 * * *',next:'20:00 MMT',model:'default',status:'ok'}
    ]})); return;
  }

  if (req.url === '/api/ollama') {
    var olData = await pingOllama();
    if (olData && olData.models) {
      res.writeHead(200,{'Content-Type':'application/json'});
      res.end(JSON.stringify({ok:true,models:olData.models.map(function(m){return {name:m.name||m.model,size:m.size||0,modified:m.modified_at||''};})})); return;
    }
    res.writeHead(200,{'Content-Type':'application/json'});
    res.end(JSON.stringify({ok:false,models:[]})); return;
  }

  res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});
  res.end(HTML);
});

server.on('error',function(e){
  if(e.code==='EADDRINUSE'){console.log('\nPort '+PORT+' busy. Kill: kill -9 $(lsof -ti:'+PORT+')\n');process.exit(1);}
});

server.listen(PORT,'127.0.0.1',function(){
  console.log('\n  Ski Mission Control v4 - Claude Edition\n');
  console.log('  http://localhost:'+PORT+'\n');
  console.log('  + Ollama live status (:11434)');
  console.log('  + Binance-style dark terminal UI');
  console.log('  + Ticker bar with live metrics\n');
});